<template lang="pug">
<div class="cc-terms cc-page">
  header.cc-terms__header.cc-header
    h1.cc-title Bases generales del concurso
    .cc-terms__content
      p CERVECERÍA CHILE S.A. sociedad anónima del giro de su denominación, RUT No 96.547.710-1, representada por José Antonio Alonso Sánchez, chileno, cédula de identidad N° 15.376.635-5, y Emanuel Caro, cédula nacional de identidad N°26.088.420-4, todos con domicilio en Avenida Presidente Eduardo Frei Montalva N° 9600, comuna de Quilicura, en adelante “Cervecería Chile” efectuará un concurso denominado “Pilsen del Sur Trivia” en adelante e indistintamente el “Concurso”, para su línea de productos “Pilsen del Sur”. El Concurso se regulará mediante las presentes bases y condiciones establecidas en este documento, en adelante las “Bases”.
      p <b>I.- ALCANCE Y DURACIÓN.</b>
      p 1. Las personas que participen en el Concurso, por el hecho de su sola participación, aceptan de pleno derecho todas y cada una de las disposiciones y condiciones descritas en estas Bases, copia de las cuales estarán disponibles, en todo momento, para su revisión y consulta en el perfil de Instagram de Pilsen del Sur, @pilsendelsur
      p 2. Podrán participar todas aquellas personas naturales, mayores de 18 años de edad, residentes o domiciliados en la República de Chile, en la medida que cumplan con lo establecido en la sección “Mecanismo de participación” de las presentes Bases. Para poder participar oficialmente, los usuarios deberán dar cumplimiento a la totalidad de los pasos indicados. A partir de tal momento, los usuarios se denominarán los “Participantes”.
      p 3. El Concurso es válido dentro del territorio de la República de Chile, y tendrá una vigencia desde el 27 de mayo de 2021 a las 12:00 horas, hasta el 20 de junio de 2021 hasta las 12:00 horas. Lo anterior, es sin perjuicio que Cervecería Chile deba o decida extender el plazo de vigencia del Concurso, fundando en motivos plausibles o determinados por casos fortuitos o fuerza mayor, hecho que, de ocurrir, será informado oportuna y adecuadamente a los Participantes a través de la página web previamente señalada, y/o por medio de cualquier otro medio oficial que sea utilizado para efectos comunicacionales. Con todo, Cervecería Chile se reserva el derecho a poner término anticipado al Concurso, fundando ello en motivos plausibles, caso fortuito o de fuerza mayor, informando con la debida antelación a los usuarios y Participantes en la referida página web, sin que lo anterior genere responsabilidades ni compensaciones de ningún tipo a favor de éstos ni de terceros.
      p <b>II.- MECANISMO DE PARTICIPACIÓN.</b>
      p 4. Para participar en el Concurso, los Participantes deberán:
      p i) Entrar a la página web http://www.pilsendelsur.com/ y registrarse para participar en la “trivia”
      p ii) Luego, los concursantes deben leer la información proporcionada en la website para poder aprender sobre Pilsen del Sur y así responder las preguntas de forma correcta. 
      p iii) Después, deben responder las 10 preguntas de 4 alternativas cada una, con eso se finaliza el proceso y ya estarán participando.
      p iv) NO podrán participar: a. Personas menores de 18 años.
      p 5. Se hace presente que, el o los Participante(s) ganador(es) de los premios ofrecidos en virtud del Concurso, al momento de canjear sus premios, no podrán compartir con otros Participantes no ganadores y/o con quienes no han cumplido con el proceso de participación previamente señalado, los códigos que son enviados por Cervecería Chile para la entrega de los beneficios.
      p <b>III.-MECÁNICA DE PREMIACIÓN.</b>
      p i) La página web irá generando un ranking de manera automática con los concursantes según los puntajes obtenidos en la trivia, mientras más puntaje obtengan, más arriba quedarán en el ranking. Este ranking se irá actualizando cada 24hrs. El día 20 de junio a las 12:00hrs. Se detendrá el concurso y los concursantes que se encuentren en los primeros 15 lugares serán los ganadores.
      p ii) Se contactarán a los ganadores a través del mail otorgado en el registro del concurso, y se esperará un máximo de 8 horas para obtener respuesta de cada uno. Si estos no responden dentro del plazo establecido, se contactarán a los concursantes siguientes en el ranking según el orden establecido. En caso de no responder, este proceso se repetirá sucesivamente hasta identificar a un ganador y este responda. 
      p <b>IV.- PREMIOS:</b>
      p El ganador o ganadora del concurso recibirá: Premio: Meet and Greet con los jugadores del Colo Colo Iván Morales y Maximiliano Falcón a través de una reunión por Zoom. Esta reunión es grupal, por lo que los 15 ganadores estarán en el mismo Zoom con los jugadores previamente mencionados. Además, cada ganador obtendrá un año de Pilsen del Sur gratis, equivalente a 12 cajas de 24 latas cada una. Cada lata tendrá 354cc). Este premio se entregará en dos tandas de 6 cajas cada una. Las entregas se realizarán una vez cada tres meses, siendo el primer despacho durante el mes de junio.
      p <b>.- ACEPTACIÓN DE LAS BASES Y AUTORIZACIÓN.</b>
      p 10. Se entenderá que todas las personas que directa o indirectamente formen parte del Concurso, como participante o en cualquier otra forma, conocen y han aceptado íntegramente estas Bases, así como las eventuales modificaciones que las mismas puedan sufrir, y que se comunicarán oportunamente a través de los canales de comunicación establecidos por Cervecería Chile, en caso de existir. 
      p 11. Los Participantes ganadores del Concurso, junto con aceptar las Bases del Concurso, deberán autorizar a Cervecería Chile para divulgar su imagen y nombre en la forma que esta última estime conveniente, pudiendo comunicar la identidad del Participante Ganador, grabar, filmar y/o fotografiarlo, así como también exhibir tales grabaciones, filmaciones y/o fotografías en cualquier medio de comunicación social, y/o a través de cualquier medio digital, incluyendo Internet. En virtud de la autorización señalada precedentemente, el Participante ganador renuncia a cualquier compensación y/o contraprestación por el uso que Cervecería Chile haga de su imagen y/o nombre en las formas antes indicadas.
      p 12. Este es un Concurso realizado por Cervecería Chile, por lo que toda información, pregunta o reclamo relacionados con el concurso y las presentes Bases, serán de exclusiva responsabilidad de Cervecería Chile.
      p 13. Información al Consumidor y responsabilidad: Cervecería Chile no se hace responsable por los gastos asociados a la participación de los Participantes en el Concurso. En este contexto, todos los trámites y gastos asociados a la participación en el mismo, cualquiera sea su naturaleza o especie, serán de responsabilidad exclusiva del Participante ganador, sin que Cervecería Chile asuma responsabilidad alguna al efecto.
      p 14. La correcta aplicación de las presentes Bases del Concurso por parte de Cervecería Chile, no dará derecho a reclamo alguno en contra de Cervecería Chile, ni de sus ejecutivos, trabajadores o personeros relacionadas. Lo anterior, especialmente en caso que Cervecería Chile se niegue a hacer entrega de cualquier premio por estimar que el Participante ganador no ha cumplido con las reglas establecidas al efecto en las presentes Bases, sin perjuicio de las acciones que la Ley reconoce a los consumidores al efecto para exigir el cumplimiento forzado de lo ofrecido en virtud del presente instrumento.
      p 15. Cervecería Chile se reserva el derecho de modificar total y/o parcialmente las Bases de este Concurso, debiendo comunicar dicha circunstancia al público a través de las Redes Sociales de la marca o de otros medios utilizados como canales oficiales para la comunicación de información relativa al presente Concurso. La modificación total o parcial de las Bases no generará responsabilidad ni compensaciones alguna a favor de terceros y/o de los Participantes, siempre que no vulnere derechos adquiridos por éstos ni altere el contenido esencial de las Bases ni del Concurso, sin haberlo comunicado oportunamente.
      p 16. El incumplimiento de las condiciones o procedimientos establecidos por Cervecería Chile para la participación de este Concurso, implica la inmediata exclusión del Participante en el Concurso y/o la revocación de los premios obtenidos por el Participante ganador.
      p 17. Cervecería Chile se reserva el derecho a iniciar las acciones legales que procedan en caso de detectar irregularidades durante el Concurso y de descalificar inmediatamente a los Participantes que hubieren intervenido en dichas irregularidades. VI.- PROHIBICIÓN DE PARTICIPAR.
      p 18. No pueden participar en este Concurso las personas menores de 18 años de edad, el personal de Cervecería Chile, de las agencias publicitarias, y proveedores involucrados en este Concurso, ni sus cónyuges y/o parientes por afinidad y consanguinidad en toda la línea recta y colateral hasta el segundo grado inclusive, ya sea que lo hagan en nombre propio y/o de terceros.
      p 19. No podrán participar en este Concurso personas que comenten más de una posibilidad en el comentario
      p <b>VII.-EXENCIÓN DE RESPONSABILIDAD.</b>
      p 19. Cervecería Chile no será responsable por los daños y perjuicios que pudiera sufrir el Participante ganador o terceros, en sus personas o bienes, con motivo o con ocasión de la participación en el Concurso y/o con motivo o en ocasión del retiro de los Premios y/o utilización de los mismos.
      p 20. Cervecería Chile podrá suspender, modificar o cancelar el Concurso en caso que se presenten casos fortuitos, fuerza mayor y/o circunstancias extraordinarias o imprevistas que no le permitan llevar a cabo el Concurso, sin que los Participantes tengan derecho a efectuar reclamo alguno.
      p 21. Finalmente, se deja expresamente establecido que Cervecería Chile es la única habilitada para la interpretación y/o aplicación de estas Bases, pudiendo en consecuencia, decidir unilateralmente sobre la interpretación y/o aplicación de cualquier punto o cuestión que estuviese o no estuviese contemplada expresamente en éstas. VIII.- PROTOCOLIZACIÓN DE LAS BASES.
      p 21. Las presentes Bases se protocolizarán en la Notaría de Santiago de don Patricio Raby Benavente. Una copia de la protocolización de estas Bases se mantendrá en las oficinas de Cervecería Chile, ubicadas en Avda. Presidente Eduardo Frei Montalva No 9.600, comuna de Quilicura.
      p José Antonio Alonso Sánchez
      p(style="text-align: center;") Gerente Legal y de Asuntos Corporativos Cervecería Chile S.A.
      img(src="", alt="alt" style="text-align: center;")
      p(style="text-align: center;") _________________________
      p(style="text-align: center;") Emanuel Caro
      p(style="text-align: center;") Gerente de Ventas Cervecería Chile S.A.
</div>
</template>

<script>
export default {
  name: "TerminosCondiciones",
};
</script>
