<template lang="pug">
<div class="cc-terms cc-page">
  header.cc-terms__header.cc-header
    h1.cc-title ACUERDO DE PRIVACIDAD
    .cc-terms__content
      p Política de privacidad de la información personal entregada por el Usuario. Cervecería Chile S.A., sus sociedades relacionadas, controladas, afiliadas y/o vinculadas (en adelante, indistintamente “AB InBev”) está comprometida a proteger la privacidad de los visitantes y/o usuarios al sitio web: http://www.pilsendelsur.com, (en adelante, indistintamente los “Visitantes” o “Usuarios”).
      p Se entiende por información personal, datos de carácter personal o datos personales, los relativos a cualquier información concerniente a personas naturales, identificadas, identificables o identificatorias, tales como el nombre, apellido, domicilio, ciudad, provincia, código postal u otras informaciones similares del Usuario, conforme a lo dispuesto en la Ley 19.628 del 28 de agosto de 1999, sobre protección de la vida privada (la “Ley 19.628”).
      p A su vez, cuando el Sitio habla de tratamiento de datos personales, se hace referencia a cualquier operación o complejo de operaciones o procedimientos técnicos, de carácter automatizado o no, que permitan recolectar, almacenar, grabar, organizar, elaborar, seleccionar, extraer, confrontar, interconectar, disociar, comunicar, ceder, transferir, transmitir o cancelar datos de carácter personal, o utilizarlos en cualquier otra forma.
      p El Sitio recolecta información sobre los datos personales de los Usuarios, siempre que los mismos provean dicha información en forma voluntaria, consciente y expresa, debiendo en todo caso el Usuario aceptar expresamente los siguientes términos y condiciones, aplicables al tratamiento de sus datos personales.
      p Cuando el Usuario visita el Sitio, su navegador automáticamente envía una dirección de Protocolo de Internet (“IP”), el tipo de navegador que el Visitante está usando y otra información adicional y relacionada con la misma a AB InBev. Por medio del presente, el Usuario autoriza a AB InBev a usar la información que el Visitante provea para administrar el Sitio, proveer al Visitante de la información que solicite y permitir al Usuario acceder al mismo.
      p Asimismo, el Usuario autoriza que AB InBev haga uso de la información al menos para losysiguientes fines:
      p (i) Permitir que AB InBev envíe información al Visitante para que pueda participar de alguna promoción publicitaria y/o concursos que AB InBev lance u organice, y cuyas bases, términos y condiciones serán debida y oportunamente informadas al Visitante;
      p (ii) Acceder a que AB InBev se comunique con el Usuario, ya sea para enviar comunicaciones relativas al Sitio o en relación a alguno de los productos que AB InBev elabora, importa y/o comercializa;
      p (iii) Permitir que AB InBev se comunique con el Usuario para enviar comunicaciones relativas a otras actividades análogas a las indicadas en el presente instrumento, con miras a que AB InBev pueda brindar sus servicios de la mejor forma posible, dando en todo caso siempre cumplimiento a lo dispuesto en materia de protección de datos personales en la legislación vigente y aplicable al efecto;
      p (iv) Permitir que AB InBev organice, diseñe, elabore, segmente, envíe y/o dirija promociones publicitarias, acciones de marketing y/o ventas directas al Visitante; y
      p (v) Consentir a que AB InBev procese la información entregada por el Usuario para comprender mejor las necesidades del mismo, mejorar los términos y condiciones de las prestaciones y los servicios que AB InBev actualmente ofrece y presta; y/o 2
      p (vi) Permitir que AB InBev elabore estadísticas con la información entregada por el Visitante, con miras a cumplir con los fines antes mencionados.
      p Al efecto, AB InBev declara que no usará la información personal entregada por el Visitante para fines comerciales, a menos que se enmarque dentro del contexto de los servicios objeto del presente instrumento. El Sitio también podrá incluir ciertas características que permitan al Visitante comunicarse con AB InBev a través del correo electrónico o de otro medio de comunicación que el Sitio solicite, ponga a disposición, y/o que el Visitante libremente provea. En este sentido, AB InBev declara que estará facultado para enviar y responder los mensajes de correo electrónico que el Usuario envíe y usar tales informaciones para las finalidades arriba mencionadas.
      p AB InBev informa que los servicios mencionados anteriormente podrán ser prestados en forma directa por AB InBev y/o a través de terceros contratados a tales efectos. El Usuario no está obligado a proveer tal información, pero sin la misma AB InBev no podrá poner a su disposición la información que el Usuario solicite a través del Sitio, y/o participar en las promociones publicitarias y/o concursos que AB InBev lance u organice. En el momento en que el Usuario provee información personal a través del Sitio, reconoce que lo hace voluntariamente, y acepta que otorga su consentimiento libre, expreso e informado para que la información personal sea utilizada con las finalidades arriba mencionadas. Asimismo, el Usuario autoriza a que la misma sea tratada, almacenada, recopilada, cedida y/o eventualmente transferida por AB InBev a contratistas involucrados con la correcta prestación de los servicios, aun cuando pueda ser que se encuentren en países que no tengan los mismos niveles de privacidad que son exigidos en Chile.
      p En todo momento el Usuario podrá ejercer el derecho de acceso, rectificación y supresión o
      p revocación de los datos personales que voluntariamente haya proporcionado al Sitio, comunicándose con AB InBev a través de cerveza.pilsendelsurcl@gmail.com. La rectificación tendrá lugar cuando la información proporcionada sea errónea, inexacta, equívoca o incompleta, y podrá ser eliminada o cancelada, cuando la información proporcionada haya caducado o su almacenamiento carezca de fundamento legal. Tanto la rectificación como la supresión y/o revocación de información no tendrá efecto retroactivo, y la solicitud expresa del Usuario deberá constar por escrito. 
      p Se hace presente que en toda recolección de datos personales que se realice a través de encuestas, estudios de mercado o sondeos de opinión pública u otros instrumentos semejantes, AB InBev informará a los Usuarios del carácter obligatorio o facultativo de las respuestas y el propósito para el cual se está solicitando la información. La comunicación de sus resultados debe omitir las señas que puedan permitir la identificación de las personas consultadas. El Usuario podrá oponerse a la utilización de sus datos personales con fines de publicidad, investigación de mercado o encuestas de opinión, informando por escrito de lo anterior a AB InBev a través de cerveza.pilsendelsurcl@gmail.com.
      p Se hace presente que no se requerirá autorización para el tratamiento de datos personales que provengan o que se recolecten de fuentes accesibles al público, en los términos indicados en la Ley 19.628.
      p <b>Política de “cookies”.</b> AB InBev utiliza la tecnología de “cookies” en el Sitio. Las cookies son
      p porciones de información que un sitio transfiere al disco rígido de un individuo con el objeto de llevar un registro. Mejoran la experiencia online al guardar las preferencias de los usuarios mientras visitan un sitio en particular. Las cookies no contienen información personal identificable y no pueden hacer una reseña del sistema o recopilar información de su disco rígido en relación a los Usuarios. Mientras el Visitante visualiza el Sitio, AB InBev puede poner una “cookie” en su computador. Las cookies 3 temporales se utilizan con fines como el de contar el número de visitas al Sitio. Estas cookies temporales son eliminadas cuando el Visitante sale de su navegador. Una cookie permanente también puede ser almacenada por su navegador en su computador. Cuando el Usuario ingresa, este tipo de cookies da cuenta si el Usuario ha visitado el Sitio anteriormente o si es un nuevo visitante. La cookie no obtiene información personal para poder contactarlo, y tampoco extrae ninguna información de su computador. La porción de “ayuda” de la barra de herramientas en la mayoría de los navegadores le indicará cómo evitar que su navegador acepte nuevas cookies, cómo hacer para que el navegador le informe cuando usted reciba una cookie nueva, o cómo bloquear todas las cookies juntas. Cuando utiliza el Sitio, el Visitante presta su consentimiento a la transmisión de su información personal identificatoria y a su uso conforme se describe en el presente. Tenga en cuenta que esta política de privacidad resulta aplicable solamente a este Sitio, y no a otros sitios, incluyendo los sitios separados de AB InBev o de cualquiera de sus marcas, que pueden tener políticas de privacidad distintas a las presentes.
      p <b>Protección de Datos Personales.</b> La visita del Usuario al Sitio implica, o pueden implicar, la
      p realización de los siguientes tratamientos de datos personales: recogida, registro, consulta, conservación, difusión, modificación o supresión. En este sentido, tanto el Usuario como AB InBev se comprometen a cumplir con lo previsto la Ley 19.628, en las leyes que se dicten en un futuro sobre esta materia, así como cualquier otra legislación que sea aplicable en materia de protección de datos personales.
      p Las partes se comprometen a prestar la cooperación y asistencia razonables a la otra parte para garantizar el cumplimiento de las obligaciones impuestas por la Ley 19.628, y en particular 
      p cuando se trate de responder a cualquier queja o solicitud de cualquier autoridad de protección de datos aplicable o de los interesados afectados.
      p Teniendo en cuenta el estado de la técnica, el coste de la aplicación y la naturaleza, ámbito, contexto y fines del tratamiento, así como los riesgos de diversa probabilidad y gravedad que entraña el tratamiento para los derechos y libertades de las personas físicas, ambas partes se comprometen a aplicar, tanto en el momento de determinar los medios de tratamiento como en el momento del propio tratamiento, medidas técnicas y organizativas apropiadas para aplicar de forma efectiva los principios de protección de datos, a fin de cumplir los requisitos de la Ley 19.628 y proteger los derechos de los interesados. Igualmente, ambas partes se comprometen a aplicar medidas técnicas y organizativas adecuadas para garantizar un nivel de seguridad adecuado al riesgo, incluidas, entre otras cosas, las medidas de seguridad descritas en la Ley 19.628.
      p <b>Prohibición de ingreso a menores.</b> El Sitio está destinado a ser visitado por mayores de 18 años. En consideración que, en la práctica, existe una imposibilidad fáctica y tecnológica de controlar la edad de los Usuarios que ingresan al Sitio, AB InBev requiere para su ingreso, en carácter de declaración jurada, que el Usuario declare si es mayor de 18 años. Cualquier incumplimiento o falsedad respecto de dicho dato realizado por un menor de 18 años será exclusiva responsabilidad del Usuario y/o de sus padres y/o tutores. Los padres y/o tutores pueden asimismo solicitar, frente al incumplimiento o falsedad ejercida por un Usuario que sea menor, que se elimine la información de su(s) hijos(s) de la base de datos del Sitio. Si usted es un padre de familia o tutor y desea ejercer estos derechos, por favor le solicitamos nos lo haga saber contactándose por medio de cerveza.pilsendelsurcl@gmail.com.
      p Tratamiento de otra Información que el Usuario envíe. Si el Usuario usa las características de comunicación del Sitio para proveer otra información más allá de la información personal y datos identificatorios que le es solicitada, incluyendo sugerencias acerca del Sitio, ideas sobre productos y/o publicidad, así como cualquier otra información relacionada, el Usuario acepta que tal información pase a pertenecer en forma gratuita a AB InBev, y autoriza expresamente que ésta pueda ser usada, reproducida, distribuida y divulgada de cualquier forma por AB InBev.
</div>
</template>

<script>
export default {
  name: "TerminosCondiciones",
};
</script>
