<template lang="pug">
<div class="cc-terms cc-page">
  header.cc-terms__header.cc-header
    h1.cc-title TÉRMINOS Y CONDICIONES
    .cc-terms__content
      p Los presentes términos y condiciones de <b>“Pilsen del Sur Trivia”</b> en adelante indistintamente los “Términos y Condiciones” y/o los “T&C”; las Bases Generales Legales del Concurso “Pilsen del Sur Trivia”, en adelante las “Bases Legales”; y el concurso propiamente tal, en adelante el “Concurso”, serán los documentos que regularán el proyecto <b>“Pilsen del Sur Trivia”</b> que Cervecería Chile S.A. está desarrollando.
      p <b>“Pilsen del Sur Trivia”</b> ofrece al Usuario, a través del Sitio Web, toda la información, herramientas y servicios disponibles para que hagan uso de dichas plataformas para la prestación de sus servicios, términos que se definirán en el punto 1 siguiente de los presentes T&C.
      p Se hace presente que, antes de hacer uso de los Servicios prestados por <b>“Pilsen del Sur Trivia”</b>, en virtud del presente instrumento, en adelante indistintamente el “Servicio” o los “Servicios”, el Usuario, deberá aceptar todos los términos, condiciones y políticas aquí establecidas. En atención a lo anterior, en el momento en que el Usuario ingresa al Sitio Web, y hace uso del Servicio prestado por <b>“Pilsen del Sur Trivia”</b> a través de las plataformas disponibles al efecto, acepta los presentes T&C, incluidos todos los instrumentos y las políticas a las que adicionalmente se hace referencia en el presente documento.
      p Estos T&C aplican a todos los Usuarios del Sitio, incluyendo sin limitación alguna a todos aquellos que tengan la calidad de navegadores, proveedores, clientes, comerciantes, y/o colaboradores de contenido.
      p El Usuario debe leer los presentes T&C cuidadosamente antes de acceder a los mismos y/o utilizar el Sitio Web. Al acceder o utilizar cualquier parte del Sitio, está aceptando los presentes T&C. En caso que el Usuario no esté de acuerdo con todos los Términos y Condiciones aquí dispuestos, no deberá acceder al Sitio Web, ni hacer uso de los Servicios ofrecidos en los mismos.
      p <b>1. DEFINICIONES</b>
      p Además de los Términos y Condiciones en su caso definidos en los párrafos que preceden, para efectos de estos Términos y Condiciones se entenderá por:
      p ·<b> Sitio Web.-</b> La dirección electrónica https: http://www.pilsendelsur.com a través de la cual se podrá hacer uso de los Servicios, sujetándose los Usuarios a los presentes Términos y Condiciones y al Aviso de Privacidad.
      p · <b>Cuenta Usuario o Cuenta del Usuario.-</b> Al registro individual del Usuario que lo identificará y distinguirá como tal de los demás usuarios, misma que será necesaria para el uso del Servicio.
      p · <b>Usuario o Visitante.-</b> A la persona física mayor de edad y que cuente con capacidad de ejercicio, conforme a las leyes de la República de Chile, y que cumpla con los requisitos de contratación, ingrese al Servicio y obtenga su Cuenta individual de Usuario en el Sitio Web. El Usuario es responsable de mantener la información de su cuenta, incluyendo los datos de su Usuario, como confidenciales reconociendo que es responsable de todas las actividades que se desarrollen utilizando su cuenta o contraseña.
      p · <b>Proveedor.- </b>Cervecería Chile S.A. y/o AB InBev Chile, entidad que para todos los efectos legales tiene su domicilio en Avenida Presidente Eduardo Frei Montalva 9600, Quilicura, Santiago de Chile.
      p · <b>Territorio:</b> La República de Chile, limitándose a las áreas de cobertura de Servicio. Para mayor información consulta http://www.pilsendelsur.com.
      p <b>Servicio(s): </b>Juego denominado “trivia” dentro del sitio web, donde los usuarios deben responder 10 preguntas de 4 alternativas cada una sobre la cerveza Pilsen del Sur y sus atributos de marca, además de preguntas sobre el sponsorship del Colo Colo. Este juego, tiene como premio un Meet and Greet con 2 jugadores del Colo Colo, Iván Morales y Maximiliano Falcón, a través de un Zoom y también un año de Pilsen del Sur (12 cajas de 24 latas 354cc) para cada ganador (15 ganadores en total). al cumplir las funciones del cargo especificadas en las Bases Legales del concurso publicadas en el Sitio Web.
      p En caso de haber más definiciones en el cuerpo de los presentes Términos y Condiciones, se señalará enseguida su significado. Se hace presente que los términos referidos en este apartado tendrán igual significado, ya sea que se utilicen en singular o plural.
      p <b>2. CONDICIONES GENERALES</b>
      p El Usuario se compromete, además de lo establecido en los Términos y Condiciones, a: (i) utilizar el Sitio Web de conformidad con su naturaleza y tal como fue autorizado y autorizado por el Proveedor, únicamente para uso personal; (ii) no copiar, distribuir, comercializar, aplicar ingeniería inversa, hackear, usar ninguna parte del Sitio Web , salvo por el uso permitido, sin la autorización previa y por escrito, del Proveedor; (iii) no alterar, modificar, ni intentar alterar o modificar en ninguna parte del Sitio Web; y (d) no compartir el Sitio Web o su contenido con personas menores de edad.
      p <b>Acceso a los Servicios por parte del Usuario. </b>Para poder tener acceso a los Servicios, el Usuario deberá crear una Cuenta Usuario al entrar por primera vez al sitio web, que tendrá el carácter de personal e intransferible, y por ende, no podrá ser utilizada por otra persona. La Cuenta del Usuario deberá ser generada con información veraz, pertinente y completa, debiendo informar inmediatamente al Proveedor sobre cualquier falla de seguridad o uso no autorizado de la Cuenta Usuario. El Proveedor no será responsable de las pérdidas que se hayan causado por cualquier uso no autorizado de la Cuenta del Usuario. Por su parte, el Usuario reconoce y acepta expresamente que él será el responsable de las pérdidas causadas al Proveedor o a otros debido a dicho uso no autorizado.
      p <b>“Pilsen del Sur Trivia”</b> se reserva el derecho de rechazar la prestación de Servicio a cualquier Usuario, por cualquier motivo y en cualquier momento durante la vigencia de los presentes T&C, si de acuerdo al criterio del Proveedor, el Usuario está haciendo un uso indebido de los mismos.
      p <b>3. DE LA INFORMACIÓN</b>
      p El Proveedor no se hace responsable si la información que proporciona el Usuario en este Sitio Web no es exacta, veraz, pertinente, completa actual y/u oportuna. El material en el Sitio Web es provisto sólo para información general y no debe confiarse en ella o utilizarse como la única base para la toma de decisiones sin consultar primeramente, información más precisa, completa u oportuna. Cualquier dependencia en la materia de este Sitio es bajo el propio riesgo del Usuario. El Sitio puede contener cierta información histórica. La información histórica, no es necesariamente actual y es provista únicamente para referencia del Usuario. “Pilsen del Sur Trivia” se reserva el derecho de modificar los contenidos del Sitio Web en cualquier momento, sin tener la obligación de actualizar la información que es proporcionada por el Usuario y publicada en el Sitio Web. Aceptas que es tu responsabilidad monitorear periódicamente los cambios en nuestro Sitio Web.
      p El Proveedor no será responsable por cualquier modificación, cambio de precios, información y/o suspensión o discontinuidad de la información proporcionada por los Usuarios.
      p <b>4. LIMITANTES</b>
      p El Proveedor se reserva el derecho de rechazar o negar la generación de una Cuenta de Usuario correspondiente cuando el Usuario caiga en alguno de los siguientes supuestos:
      p · Solamente se podrá crear una Cuenta de Usuario. Aquel Usuario que cuente con dos o más registros será inhabilitado.
      p · Cualquier intento de fraude, hackeo, interferencia al sistema o al Sitio Web , cualquier sospecha de fraude o alteración del sistema, generación de bots automáticos y/o actividades análogas o similares, provocará la baja o eliminación de la Cuenta de Usuario en el Sitio Web.
      p · El incumplimiento con cualquiera de los puntos contenidos en estos Términos y Condiciones (y sus consiguientes versiones actualizadas) determinará la inhabilitación del Usuario.
      p · La información proporcionada por los Usuarios deberá ser real, precisa, clara y comprobable, en caso de incumplimiento su Cuenta automáticamente será inhabilitada en el Sitio Web.
      p · Se utilice y/o se cargue cualquier información en la que:
      p a) usen palabras y/o imágenes altisonantes, violentas, ofensivas, discriminatorias, que vayan en contra de la moral y las buenas costumbres,
      p b) se muestren personas consumiendo o manipulando cerveza o cualquier otra bebida alcohólica o sustancia psicotrópica y/o ilegal, que hagan alusión a la manipulación o consumo de cerveza o cualquier otra bebida alcohólica o sustancia psicotrópica y/o ilegal, que relacionen directa o indirectamente o hagan alusión a menores de 18 años,
      p c) claramente infrinja derechos de terceros,
      p d) sea considerada inapropiada por cualquier motivo a entera discreción del Proveedor,
      p dicha información será eliminada inmediatamente, y el Usuario será inhabilitado.
      p <b>5. INFORMACIÓN PERSONAL</b>
      p La presentación de datos personales o de aquella información que tenga la calidad de personal por parte del Usuario a través del Sitio Web, se rige por lo dispuesto en la Política de Privacidad, disponible en el siguiente link: http://www.pilsendelsur.com.
      p <b>6. USOS PROHIBIDOS</b>
      p En adición a otras prohibiciones establecidas en estos Términos y Condiciones, se prohíbe el uso del Sitio Web o su contenido: (i) para ningún propósito o acto ilegal; (ii) para pedirle a otros que realicen o participen en actos ilícitos; (iii) para violar cualquier regulación, reglas, leyes internacionales, nacionales, estatales y locales; (iv) para infringir o violar el derecho de propiedad intelectual e industrial y/o derechos de autor propiedad del Proveedor o de terceros; (v) para acosar, abusar, insultar, dañar, difamar, calumniar, desprestigiar, intimidar o discriminar por razones de género, orientación sexual, religión, etnia, raza, edad, nacionalidad o discapacidad, o cualquier otro motivo; (vi) para presentar información falsa o engañosa; (vii) para cargar o transmitir virus o cualquier otro tipo de código malicioso que sea o pueda ser utilizado en cualquier forma que pueda comprometer la funcionalidad o el funcionamiento del Servicio o de cualquier sitio web relacionado al mismo, y/u otros sitios webs o dispositivos; (viii) para recopilar o rastrear información personal de otros; (ix) para generar spam, phish, pharm, pretext, spider, crawl, or scrape; (j) para cualquier propósito obsceno o inmoral; o (x) para interferir con o burlar los elementos de seguridad del Servicio, Sitio Web y/o cualquier sitio web relacionado. El Proveedor se reserva el derecho de suspender el uso del Servicio o de cualquier sitio web relacionado, en caso que el Usuario viole o vulnere cualquiera de los ítems de usos prohibidos antes indicados, y/o en aquellas circunstancias en que el Proveedor considere que el Usuario esté actuando de mala fe y/o esté haciendo un mal uso del Servicio.
      p <b>7. LIMITACIÓN DE RESPONSABILIDAD</b>
      p El Proveedor no garantiza ni asegura que el uso del Servicio proporcionado a través del Sitio Web 
      p será ininterrumpido, puntual, seguro y/o libre de errores. Al aceptar estos Términos y Condiciones, el Visitante acepta que de vez en cuando el Proveedor pueda suspender el Servicio por períodos de tiempo indefinidos o bien cancelar el Servicio en cualquier momento sin previo aviso, con motivo de fallas técnicas y/o inconvenientes particulares. En ningún caso el Proveedor, sus directores, funcionarios, empleados, afiliados, agentes, contratistas, internos, proveedores, prestadores de servicios o licenciantes serán responsables por cualquier daño, pérdida, reclamo, o daños directos, indirectos, incidentales, punitivos, especiales o consecuentes de cualquier tipo.
      p <b>8. DIVISIBILIDAD</b>
      p En el caso de que se determine que cualquier disposición de estos Términos y Condiciones de Servicio sea ilegal, nula o inejecutable, dicha disposición será, no obstante, efectiva a obtener la máxima medida permitida por la ley aplicable, y la parte no exigible se considerará separada de estos Términos y Condiciones, dicha determinación no afectará la validez de aplicabilidad de las demás disposiciones restantes.
      p <b>9. MODIFICACIÓN A LOS TÉRMINOS Y CONDICIONES</b>
      p El Usuario puede revisar la versión más actualizada de los Términos y Condiciones en cualquier momento en el Sitio Web.
      p El Proveedor se reserva el derecho, a su sola discreción y sin necesidad de notificar y/o de enviar un aviso previo al Usuario, de actualizar, modificar, corregir, enmendar, aclarar o reemplazar cualquier parte de estos Términos y Condiciones, mediante la correspondiente publicación de las actualizaciones y los cambios en el Sitio Web. Es responsabilidad de los Usuarios revisar el Sitio Web periódicamente para verificar los cambios. El uso continuo de o el acceso al Sitio Web o el Servicio después de la publicación de cualquier cambio en estos Términos y Condiciones de Servicio, implica la aceptación de dichos cambios por parte del Usuario.
      p <b>10. USO DE COOKIES</b>
      p El Sitio Web y/o APP utiliza y/o podrá utilizar cookies, archivos temporales y otras herramientas (en adelante conjunta e indistintamente como las “cookies”) para facilitar el acceso al Sitio Web o APP. Asimismo, el navegador o dispositivo que se utilice podrá generar cookies que permitan la operación de otras. Puede desactivarlas y/o eliminarlas mediante las opciones de privacidad de su navegador de Internet; en el entendido que ello podría afectar el uso del Sitio Web y/o APP, así como el acceso a los Servicios. No obstante lo anterior, al seguir navegando en el Sitio Web y/o en la APP significa que aceptas el uso de cookies.
      p <b>11. INFORMACIÓN DE CONTACTO</b>
      p La información de contacto que nos proporcionen los Usuarios será resguardada como confidencial y utilizada de conformidad con lo establecido en las Políticas de Privacidad, las cuales se encuentran en el sitio web http://www.pilsendelsur.com y en la legislación vigente y aplicable al efecto.
      p <b>12. AUTORIZACIÓN USO DE IMAGEN / OBRAS</b>
      p Al aceptar estos Términos y Condiciones los Usuarios autorizan al Proveedor a utilizar su imagen, fotografías, obras, marcas, para (i) la prestación de los Servicios, (ii) la elaboración de material fotográfico o digital, (iii) realizar grabaciones de audio y video a ser utilizados en los Servicios prestados a través del Sitio WEB, así como en medios de comunicación que el Proveedor juzgue convenientes para efectos publicitarios a través de cualquier medio en Chile y/o en el extranjero. Los Usuarios declaran que todos los materiales a los que se hace referencia en el párrafo anterior son de su exclusiva propiedad y que cuentan con la debida autorización para utilizar los mismos en el Sitio WEB.
      p Al aceptar estos Términos y Condiciones, el Usuario otorga en favor del Proveedor una
      p autorización para difundir y utilizar la información entregada para la correcta prestación de los Servicios, (i) en el Sitio Web, y/o (ii) en cualquier medio de comunicación con fines publicitarios del Sitio Web, de la manera que más convenga a los intereses del Proveedor, sin que esto implique pago alguno a los Usuarios en materia de derechos de propiedad industrial y/o intelectual. Asimismo, el Usuario garantiza que los materiales referidos en este párrafo no infringen derechos de terceros, por lo que se obliga a mantener a salvo al Proveedor en caso de reclamos de cualquier naturaleza por parte de terceros sobre materiales cargados al Sitio WEB por parte de los Usuarios. Sin perjuicio de lo anterior, las partes reconocen que todas las marcas, dominios, softwares, patentes, imágenes, fotografías, sonido, audio, vídeo, diseño, código fuente, contenidos, textos, gráficos, bases de datos, entre otros relacionados con la identificación y uso del Sitio Web, son de propiedad del Proveedor y están protegidos por las leyes y los tratados internacionales de derecho de autor, marcas, patentes, modelos y diseños industriales. Queda expresamente prohibida su reproducción, distribución o difusión, sin la autorización expresa y escrita del Proveedor.
      p Ninguna marca, diseño, logo, producto, imagen o sonido que pertenezca al Proveedor pueden ser reproducidos, duplicados, copiados, vendidos, revendidos, visitados o explotados para ningún fin, en todo o en parte, sin su consentimiento escrito previo. No se puede enmarcar o utilizar técnicas de enmarcación para encerrar alguna marca comercial, logotipo u otra información registrada o patentada (incluyendo imágenes, texto, disposición de páginas, o formulario), sin el consentimiento escrito previo del Proveedor. Tampoco se permite el uso de meta etiquetas ni ningún otro “texto oculto” que use el nombre o marcas comerciales del Proveedor, o de empresas relacionadas con el mismo, sin autorización escrita previa del mismo. Se prohíbe hacer un uso indebido de este sitio o de estas marcas, licencias o patentes. Lo anterior, sin perjuicio de las excepciones expresamente señaladas en la ley 17.336 sobre propiedad intelectual y demás normas o tratados internacionales que resulten aplicables en Chile.
      p <b>13. AVISO DE PRIVACIDAD.</b>
      p El Proveedor hace del conocimiento de los Usuarios que podrán consultar en cualquier momento el Aviso de Privacidad en: Políticas de Privacidad, encontradas en http://www.pilsendelsur.com.
      p <b>14. SOPORTE A USUARIOS</b>
      p Los Usuarios podrán contactar al Proveedor a través de cerveza.pilsendelsurcl@gmail.com para despejar cualquier duda, comentario, queja y/o sugerencia, así como para recibir asistencia respecto del funcionamiento del Sitio Web.
</div>
</template>

<script>
export default {
  name: "TerminosCondiciones",
};
</script>
